INCLUDE memory.x

REGION_ALIAS("ROTEXT", IRAM);
REGION_ALIAS("RODATA", DRAM);

REGION_ALIAS("RWDATA", DRAM);
REGION_ALIAS("RWTEXT", IRAM);

REGION_ALIAS("RTC_FAST_RWTEXT", RTC_FAST);
REGION_ALIAS("RTC_FAST_RWDATA", RTC_FAST);

/* include linker script from esp-hal */
INCLUDE bl-riscv-link.x
INCLUDE rom-functions.x